- name: Configure Web Servers
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache and Nginx
      package:
        name:
          - apache2
          - nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable we servers
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - nginx
